### ISSUE TITLE
Update to @huggingface/transformers@3.0.0

### ISSUE THREAD

**Issue by zcbenz** [lenML/tokenizers#6]
It is the official stable release and includes some fixes for legacy tokenizers.

**Comment by zhzLuke96** [comment]
thx feedback~

However, based on my review, the update from `transformers@3.0.0-alpha.19` to `transformers@3.0.0` did not involve any code changes to the tokenizers, only some modifications to URLs in the comments. Therefore, I don't think it's necessary to sync our library's code for this update.  

Since `tokenizer.js` is just a small part of the `transformers` library, we don't need to sync with every version update.

**Comment by zcbenz** [comment]
Thanks for looking into this, somehow I have a model's tokenizer failed to load in this module but succeeded in upstream, I'll take a closer look.

**Comment by zcbenz** [comment]
My bad, it turns out I forgot to update package.json!
